# U.S. Medical Insurance Costs

In [1]:
# import csv
import csv

In [13]:
with open('insurance.csv', 'r') as file:
    reader = csv.DictReader(file)
    data = list(reader)
#     print(data)
    
# printing first 5 rows
for row in data[:5]:
    print(row)

{'age': '19', 'sex': 'female', 'bmi': '27.9', 'children': '0', 'smoker': 'yes', 'region': 'southwest', 'charges': '16884.924'}
{'age': '18', 'sex': 'male', 'bmi': '33.77', 'children': '1', 'smoker': 'no', 'region': 'southeast', 'charges': '1725.5523'}
{'age': '28', 'sex': 'male', 'bmi': '33', 'children': '3', 'smoker': 'no', 'region': 'southeast', 'charges': '4449.462'}
{'age': '33', 'sex': 'male', 'bmi': '22.705', 'children': '0', 'smoker': 'no', 'region': 'northwest', 'charges': '21984.47061'}
{'age': '32', 'sex': 'male', 'bmi': '28.88', 'children': '0', 'smoker': 'no', 'region': 'northwest', 'charges': '3866.8552'}

In [15]:
# Total number of rows
data_length = len(data)
print(data_length)

1338

In [22]:
# column names
print(reader.fieldnames)

# or

columns = data[0].keys()
print("Columns:", columns)

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']
Columns: dict_keys(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'])

In [33]:
# Unique values of sex, region, smoker

unique_sex = set()
unique_region = set()
unique_smoker = set()

for row in data:
    unique_sex.add(row['sex'])
    unique_region.add(row['region'])
    unique_smoker.add(row['smoker'])
    
print(f"Unique Sex : {list(unique_sex)}")
print(f"Unique Region : {unique_region}")
print(f"Unique Smoker : {unique_smoker}")

# or

# unique_sex = []
# unique_region = []
# unique_smoker = []

# for row in data:
#     if row['sex'] not in unique_sex:
#         unique_sex.append(row['sex'])
#     if row['region'] not in unique_region:
#         unique_region.append(row['region'])
#     if row['smoker'] not in unique_smoker:
#         unique_smoker.append(row['smoker'])

# print(f"Unique Sex : {unique_sex}")
# print(f"Unique Region : {unique_region}")
# print(f"Unique Smoker : {unique_smoker}")

Unique Sex : ['male', 'female']
Unique Region : {'southeast', 'northeast', 'northwest', 'southwest'}
Unique Smoker : {'no', 'yes'}
Unique Sex : ['female', 'male']
Unique Region : ['southwest', 'southeast', 'northwest', 'northeast']
Unique Smoker : ['yes', 'no']

In [40]:
#  Calculate Average Insurance Cost
total_cost = 0

for row in data:
    total_cost += float(row['charges'])

average_cost = total_cost / len(data)
print("Average Insurance Cost:", round(average_cost, 2))

# or

charges = [float(row['charges']) for row in data]
average = sum(charges) / len(charges)
print("Average Insurance Cost:", round(average, 2))

Average Insurance Cost: 13270.42
Average Insurance Cost: 13270.42

In [44]:
# Find Who Pays More Smokers vs Non-smokers

smoker_cost = 0
smoker_count = 0
non_smoker_cost = 0
non_smoker_count = 0

for row in data:
    cost = float(row['charges'])
    if row["smoker"] == 'yes':
        smoker_cost += cost
        smoker_count += 1
    else:
        non_smoker_cost += cost
        non_smoker_count += 1

print(f"Average Smoker Cost: {smoker_cost / smoker_count}")
print(f"Average Non Smoker Cost: {non_smoker_cost / non_smoker_count}")

Average Smoker Cost: 32050.23183153285
Average Non Smoker Cost: 8434.268297856199

In [48]:
# Find Who Pays More Male vs Female
male_cost = 0
male_count = 0
female_cost = 0
female_count = 0

for row in data:
    cost = float(row['charges'])
    if row['sex'] == 'male':
        male_cost += cost
        male_count += 1
    else:
        female_cost += cost
        female_count += 1
        
print(f'Average Male Cost : {male_cost/male_count}')
print(f'Average Feale Cost : {female_cost/female_count}')

if male_cost / male_count > female_cost / female_count:
    print("Males pay more on average.")
else:
    print("Females pay more on average.")

Average Male Cost : 13956.751177721886
Average Feale Cost : 12569.57884383534
Males pay more on average.

In [52]:
# Group by Region Count how many people are from each region.

region_count = {}
for row in data:
    region = row['region']
    if region not in region_count:
        region_count[region] = 1
    else:
        region_count[region] += 1
        
print(f"People in each region: {region_count}")

People in each region: {'southwest': 325, 'southeast': 364, 'northwest': 325, 'northeast': 324}

In [66]:
# wtiting average age using function
age = [float(row['age']) for row in data]

average_age = sum(age) / len(age)
print(average_age)


total_age = 0
for row in data:
    age = float(row['age'])
    total_age += age

avg_age = total_age / len(data)
print(avg_age)

def get_average_age():
    total_age = 0
    for row in data:
        total_age += int(row['age'])
    return round(total_age / len(data),2)

print("Average Age:", get_average_age())

39.20702541106129
39.20702541106129
Average Age: 39.21

In [69]:
# highest payer
def highest_payer():
    high_payer = 0
    for row in data:
        high_charges = float(row['charges'])
        if high_charges > high_payer:
            high_payer = high_charges
    return high_payer

print(highest_payer())

def highest_payer_person():
    high_payer = 0
    person = None
    for row in data:
        high_charges = float(row['charges'])
        if high_charges > high_payer:
            high_payer = high_charges
            person = row
    return person


hp = highest_payer_person()
print(f"Highest Payer: {hp['sex']}, Age: {hp['age']}, Smoker: {hp['smoker']}, Charges: {hp['charges']}")

63770.42801
Highest Payer: female, Age: 54, Smoker: yes, Charges: 63770.42801

In [71]:
# calculate the oldest person
def oldest_person():
    older = 0
    person = None
    for row in data:
        age = int(row['age'])
        if age > older:
            older = age
            person = row
    return person

op = oldest_person()
print(f"Oldest Person: {op['sex']}, Age: {op['age']}, Smoker: {op['smoker']}, Charges: {op['charges']}")

Oldest Person: male, Age: 64, Smoker: no, Charges: 30166.61817

In [75]:
# People with more than 2 children

def people_with_more_than_two_child():
    child = 2
    people_list = []
    person = None
    
    for row in data:
        child_val = int(row['children'])
        if child_val > child:
            person = row
            people_list.append(person)
            
    return people_list

people = people_with_more_than_two_child()


for item in people:
    print(f"{item['sex']}, Age: {item['age']}, Children: {item['children']}, Charges: {item['charges']}")

male, Age: 28, Children: 3, Charges: 4449.462
female, Age: 37, Children: 3, Charges: 7281.5056
female, Age: 59, Children: 3, Charges: 14001.1338
female, Age: 19, Children: 5, Charges: 4687.797
female, Age: 62, Children: 3, Charges: 15612.19335
female, Age: 40, Children: 3, Charges: 8059.6791
male, Age: 43, Children: 3, Charges: 8606.2174
male, Age: 25, Children: 4, Charges: 4504.6624
male, Age: 28, Children: 3, Charges: 17663.1442
male, Age: 31, Children: 5, Charges: 6799.458
female, Age: 53, Children: 3, Charges: 11741.726
female, Age: 48, Children: 4, Charges: 11033.6617
male, Age: 59, Children: 3, Charges: 30184.9367
female, Age: 54, Children: 3, Charges: 12105.32
female, Age: 61, Children: 3, Charges: 30942.1918
male, Age: 52, Children: 3, Charges: 11488.31695
female, Age: 47, Children: 3, Charges: 10115.00885
female, Age: 54, Children: 3, Charges: 27322.73386
male, Age: 30, Children: 3, Charges: 20745.9891
female, Age: 29, Children: 3, Charges: 5138.2567
male, Age: 46, Children: 3, Charges: 40720.55105
female, Age: 32, Children: 3, Charges: 6334.34355
female, Age: 50, Children: 3, Charges: 19749.38338
male, Age: 47, Children: 4, Charges: 10407.08585
female, Age: 20, Children: 5, Charges: 4830.63
female, Age: 32, Children: 3, Charges: 6128.79745
male, Age: 27, Children: 3, Charges: 4827.90495
female, Age: 41, Children: 3, Charges: 8538.28845
male, Age: 22, Children: 3, Charges: 4005.4225
male, Age: 36, Children: 3, Charges: 43753.33705
female, Age: 30, Children: 3, Charges: 5325.651
male, Age: 40, Children: 4, Charges: 8162.71625
male, Age: 32, Children: 3, Charges: 5253.524
male, Age: 55, Children: 3, Charges: 11987.1682
female, Age: 59, Children: 3, Charges: 14001.2867
male, Age: 40, Children: 3, Charges: 7196.867
male, Age: 27, Children: 3, Charges: 4260.744
female, Age: 55, Children: 3, Charges: 13047.33235
male, Age: 51, Children: 4, Charges: 11520.09985
male, Age: 52, Children: 3, Charges: 24869.8368
female, Age: 53, Children: 3, Charges: 20462.99766
male, Age: 46, Children: 3, Charges: 46151.1245
female, Age: 59, Children: 3, Charges: 14590.63205
male, Age: 54, Children: 3, Charges: 48549.17835
male, Age: 52, Children: 3, Charges: 25992.82104
male, Age: 25, Children: 3, Charges: 3906.127
male, Age: 31, Children: 3, Charges: 38746.3551
male, Age: 36, Children: 3, Charges: 6746.7425
female, Age: 53, Children: 3, Charges: 24873.3849
male, Age: 43, Children: 3, Charges: 42124.5153
female, Age: 26, Children: 4, Charges: 24671.66334
female, Age: 49, Children: 4, Charges: 10977.2063
female, Age: 34, Children: 3, Charges: 6184.2994
male, Age: 46, Children: 3, Charges: 8944.1151
male, Age: 47, Children: 3, Charges: 9620.3307
female, Age: 56, Children: 3, Charges: 13430.265
male, Age: 18, Children: 3, Charges: 3481.868
female, Age: 39, Children: 3, Charges: 21659.9301
female, Age: 64, Children: 3, Charges: 16455.70785
female, Age: 24, Children: 3, Charges: 4618.0799
male, Age: 48, Children: 4, Charges: 10736.87075
female, Age: 43, Children: 3, Charges: 8522.003
male, Age: 49, Children: 3, Charges: 10269.46
male, Age: 38, Children: 3, Charges: 6652.5288
male, Age: 25, Children: 5, Charges: 5080.096
male, Age: 45, Children: 5, Charges: 9788.8659
female, Age: 27, Children: 3, Charges: 18804.7524
male, Age: 60, Children: 3, Charges: 13919.8229
male, Age: 35, Children: 3, Charges: 5926.846
female, Age: 52, Children: 5, Charges: 12592.5345
male, Age: 39, Children: 4, Charges: 7512.267
female, Age: 40, Children: 3, Charges: 7682.67
female, Age: 49, Children: 3, Charges: 10381.4787
male, Age: 54, Children: 3, Charges: 25382.297
male, Age: 63, Children: 3, Charges: 15555.18875
male, Age: 48, Children: 3, Charges: 9563.029
female, Age: 54, Children: 3, Charges: 12475.3513
male, Age: 21, Children: 4, Charges: 17942.106
male, Age: 37, Children: 3, Charges: 6796.86325
female, Age: 33, Children: 3, Charges: 5972.378
female, Age: 34, Children: 3, Charges: 6196.448
female, Age: 35, Children: 3, Charges: 39983.42595
female, Age: 49, Children: 5, Charges: 11552.904
male, Age: 21, Children: 3, Charges: 3861.20965
female, Age: 64, Children: 3, Charges: 16085.1275
female, Age: 34, Children: 3, Charges: 6753.038
male, Age: 37, Children: 4, Charges: 40182.246
male, Age: 36, Children: 3, Charges: 6748.5912
male, Age: 56, Children: 4, Charges: 12949.1554
male, Age: 33, Children: 5, Charges: 6666.243
male, Age: 42, Children: 3, Charges: 32787.45859
female, Age: 23, Children: 3, Charges: 4466.6214
male, Age: 48, Children: 3, Charges: 10141.1362
female, Age: 40, Children: 3, Charges: 8252.2843
female, Age: 57, Children: 4, Charges: 14394.39815
male, Age: 37, Children: 3, Charges: 6435.6237
male, Age: 30, Children: 3, Charges: 4837.5823
female, Age: 55, Children: 3, Charges: 12485.8009
male, Age: 60, Children: 3, Charges: 46130.5265
male, Age: 56, Children: 3, Charges: 12363.547
male, Age: 49, Children: 3, Charges: 10264.4421
female, Age: 31, Children: 3, Charges: 6113.23105
male, Age: 53, Children: 3, Charges: 11264.541
female, Age: 30, Children: 3, Charges: 40932.4295
male, Age: 35, Children: 3, Charges: 19361.9988
female, Age: 24, Children: 3, Charges: 4234.927
female, Age: 59, Children: 3, Charges: 14007.222
male, Age: 23, Children: 3, Charges: 36189.1017
male, Age: 24, Children: 4, Charges: 17128.42608
female, Age: 39, Children: 3, Charges: 7985.815
male, Age: 30, Children: 3, Charges: 5428.7277
male, Age: 61, Children: 3, Charges: 27941.28758
male, Age: 51, Children: 3, Charges: 10560.4917
male, Age: 35, Children: 3, Charges: 5934.3798
male, Age: 30, Children: 3, Charges: 18259.216
female, Age: 35, Children: 3, Charges: 6414.178
male, Age: 29, Children: 3, Charges: 5209.57885
female, Age: 46, Children: 3, Charges: 9414.92
female, Age: 33, Children: 3, Charges: 6360.9936
male, Age: 23, Children: 3, Charges: 3597.596
male, Age: 41, Children: 3, Charges: 39597.4072
female, Age: 49, Children: 3, Charges: 24106.91255
female, Age: 38, Children: 3, Charges: 7151.092
female, Age: 25, Children: 3, Charges: 4391.652
male, Age: 44, Children: 3, Charges: 8891.1395
male, Age: 33, Children: 5, Charges: 6653.7886
male, Age: 22, Children: 3, Charges: 3443.064
female, Age: 51, Children: 3, Charges: 46255.1125
male, Age: 25, Children: 4, Charges: 4877.98105
female, Age: 36, Children: 4, Charges: 7243.8136
male, Age: 26, Children: 3, Charges: 4661.28635
male, Age: 27, Children: 3, Charges: 4846.92015
male, Age: 63, Children: 3, Charges: 15170.069
female, Age: 59, Children: 3, Charges: 14382.70905
male, Age: 46, Children: 5, Charges: 10096.97
female, Age: 39, Children: 5, Charges: 8965.79575
male, Age: 25, Children: 3, Charges: 19933.458
male, Age: 46, Children: 3, Charges: 9500.57305
female, Age: 39, Children: 5, Charges: 8596.8278
female, Age: 50, Children: 3, Charges: 10702.6424
female, Age: 45, Children: 3, Charges: 9704.66805
male, Age: 31, Children: 3, Charges: 19199.944
male, Age: 20, Children: 5, Charges: 4915.05985
male, Age: 43, Children: 3, Charges: 8410.04685
female, Age: 27, Children: 3, Charges: 16420.49455
female, Age: 39, Children: 3, Charges: 7986.47525
female, Age: 39, Children: 3, Charges: 7418.522
female, Age: 33, Children: 3, Charges: 6551.7501
male, Age: 47, Children: 3, Charges: 24915.22085
female, Age: 61, Children: 4, Charges: 36580.28216
female, Age: 54, Children: 3, Charges: 12495.29085
female, Age: 22, Children: 3, Charges: 35595.5898
female, Age: 54, Children: 3, Charges: 12094.478
male, Age: 47, Children: 3, Charges: 25309.489
male, Age: 36, Children: 3, Charges: 6548.19505
female, Age: 29, Children: 4, Charges: 5708.867
male, Age: 63, Children: 3, Charges: 15161.5344
female, Age: 39, Children: 5, Charges: 19023.26
male, Age: 23, Children: 3, Charges: 3591.48
female, Age: 50, Children: 4, Charges: 11299.343
female, Age: 18, Children: 4, Charges: 4561.1885
male, Age: 53, Children: 3, Charges: 11253.421
male, Age: 45, Children: 3, Charges: 8605.3615
male, Age: 38, Children: 3, Charges: 41949.2441
female, Age: 48, Children: 3, Charges: 24180.9335
female, Age: 28, Children: 3, Charges: 5312.16985
male, Age: 41, Children: 5, Charges: 9222.4026
female, Age: 30, Children: 3, Charges: 5693.4305
female, Age: 53, Children: 3, Charges: 46661.4424
female, Age: 39, Children: 5, Charges: 8582.3023
female, Age: 50, Children: 3, Charges: 11085.5868
female, Age: 41, Children: 3, Charges: 7954.517
male, Age: 52, Children: 3, Charges: 11289.10925
female, Age: 43, Children: 3, Charges: 40941.2854
female, Age: 48, Children: 4, Charges: 11015.1747
female, Age: 36, Children: 3, Charges: 7228.21565
male, Age: 20, Children: 3, Charges: 37465.34375
female, Age: 19, Children: 3, Charges: 18838.70366
female, Age: 18, Children: 3, Charges: 18223.4512
female, Age: 38, Children: 3, Charges: 7537.1639
male, Age: 52, Children: 3, Charges: 60021.39897
female, Age: 54, Children: 3, Charges: 12479.70895
male, Age: 37, Children: 3, Charges: 6985.50695
female, Age: 22, Children: 3, Charges: 4296.2712
male, Age: 28, Children: 5, Charges: 5615.369
female, Age: 45, Children: 3, Charges: 9101.798
male, Age: 33, Children: 4, Charges: 6059.173
female, Age: 40, Children: 4, Charges: 15828.82173
female, Age: 51, Children: 3, Charges: 11436.73815
male, Age: 55, Children: 3, Charges: 30063.58055
male, Age: 45, Children: 3, Charges: 8615.3
male, Age: 43, Children: 5, Charges: 14478.33015
male, Age: 46, Children: 3, Charges: 9301.89355
male, Age: 62, Children: 3, Charges: 46718.16325
male, Age: 32, Children: 4, Charges: 21472.4788
female, Age: 30, Children: 3, Charges: 18765.87545
male, Age: 35, Children: 4, Charges: 19496.71917
male, Age: 31, Children: 3, Charges: 5425.02335
female, Age: 52, Children: 3, Charges: 11411.685
male, Age: 50, Children: 3, Charges: 10600.5483

In [91]:
# Smokers under age 30
def smoker_age():
    smoker = 'yes'
    age = 30
    smoker_list = []
    person = None
    for row in data:
        if smoker == row['smoker'] and age > int(row['age']):
#             person = row
            smoker_list.append(row)
    return smoker_list
persons = smoker_age()

for person in persons:
    print(f"Smoker: {person['smoker']}, Sex : {person['sex']}, Age: {person['age']}, Region: {person['region']}, Charges: {person['charges']}")

Smoker: yes, Sex : female, Age: 19, Region: southwest, Charges: 16884.924
Smoker: yes, Sex : male, Age: 27, Region: southeast, Charges: 39611.7577
Smoker: yes, Sex : male, Age: 22, Region: southwest, Charges: 35585.576
Smoker: yes, Sex : male, Age: 28, Region: southwest, Charges: 51194.55914
Smoker: yes, Sex : male, Age: 18, Region: southeast, Charges: 34303.1672
Smoker: yes, Sex : female, Age: 20, Region: northwest, Charges: 14711.7438
Smoker: yes, Sex : male, Age: 28, Region: southeast, Charges: 17663.1442
Smoker: yes, Sex : female, Age: 27, Region: southeast, Charges: 16577.7795
Smoker: yes, Sex : male, Age: 22, Region: southeast, Charges: 37165.1638
Smoker: yes, Sex : male, Age: 20, Region: northwest, Charges: 17560.37975
Smoker: yes, Sex : female, Age: 29, Region: southeast, Charges: 19107.7796
Smoker: yes, Sex : female, Age: 19, Region: southwest, Charges: 17081.08
Smoker: yes, Sex : male, Age: 18, Region: northeast, Charges: 15518.18025
Smoker: yes, Sex : female, Age: 18, Region: southeast, Charges: 36149.4835
Smoker: yes, Sex : female, Age: 27, Region: southeast, Charges: 37133.8982
Smoker: yes, Sex : male, Age: 19, Region: southwest, Charges: 34779.615
Smoker: yes, Sex : male, Age: 19, Region: northwest, Charges: 17352.6803
Smoker: yes, Sex : female, Age: 23, Region: northeast, Charges: 38511.6283
Smoker: yes, Sex : male, Age: 18, Region: northeast, Charges: 12829.4551
Smoker: yes, Sex : male, Age: 19, Region: northwest, Charges: 33750.2918
Smoker: yes, Sex : female, Age: 20, Region: southeast, Charges: 17085.2676
Smoker: yes, Sex : male, Age: 19, Region: northwest, Charges: 36219.40545
Smoker: yes, Sex : male, Age: 25, Region: southeast, Charges: 42112.2356
Smoker: yes, Sex : male, Age: 19, Region: southwest, Charges: 16297.846
Smoker: yes, Sex : female, Age: 27, Region: southwest, Charges: 34838.873
Smoker: yes, Sex : female, Age: 19, Region: southwest, Charges: 13844.506
Smoker: yes, Sex : male, Age: 26, Region: southwest, Charges: 36085.219
Smoker: yes, Sex : female, Age: 23, Region: northwest, Charges: 18033.9679
Smoker: yes, Sex : male, Age: 24, Region: southeast, Charges: 38126.2465
Smoker: yes, Sex : female, Age: 27, Region: northeast, Charges: 15006.57945
Smoker: yes, Sex : female, Age: 26, Region: northeast, Charges: 14455.64405
Smoker: yes, Sex : male, Age: 24, Region: northeast, Charges: 35147.52848
Smoker: yes, Sex : male, Age: 21, Region: southwest, Charges: 17942.106
Smoker: yes, Sex : male, Age: 29, Region: southwest, Charges: 36197.699
Smoker: yes, Sex : male, Age: 19, Region: southeast, Charges: 32548.3405
Smoker: yes, Sex : female, Age: 21, Region: northeast, Charges: 15359.1045
Smoker: yes, Sex : female, Age: 19, Region: northwest, Charges: 17468.9839
Smoker: yes, Sex : female, Age: 19, Region: southeast, Charges: 34439.8559
Smoker: yes, Sex : male, Age: 18, Region: northeast, Charges: 34617.84065
Smoker: yes, Sex : male, Age: 27, Region: southeast, Charges: 34806.4677
Smoker: yes, Sex : female, Age: 29, Region: northeast, Charges: 16657.71745
Smoker: yes, Sex : male, Age: 23, Region: northeast, Charges: 36189.1017
Smoker: yes, Sex : male, Age: 29, Region: southwest, Charges: 44585.45587
Smoker: yes, Sex : male, Age: 27, Region: southeast, Charges: 18246.4955
Smoker: yes, Sex : male, Age: 18, Region: southeast, Charges: 36307.7983
Smoker: yes, Sex : female, Age: 19, Region: northwest, Charges: 17748.5062
Smoker: yes, Sex : male, Age: 27, Region: northwest, Charges: 18310.742
Smoker: yes, Sex : female, Age: 18, Region: southeast, Charges: 38792.6856
Smoker: yes, Sex : female, Age: 23, Region: southeast, Charges: 36021.0112
Smoker: yes, Sex : male, Age: 25, Region: northwest, Charges: 15817.9857
Smoker: yes, Sex : male, Age: 18, Region: northeast, Charges: 33732.6867
Smoker: yes, Sex : male, Age: 25, Region: southwest, Charges: 19933.458
Smoker: yes, Sex : male, Age: 29, Region: northeast, Charges: 16138.76205
Smoker: yes, Sex : female, Age: 24, Region: northeast, Charges: 14571.8908
Smoker: yes, Sex : female, Age: 27, Region: northwest, Charges: 16420.49455
Smoker: yes, Sex : male, Age: 24, Region: southwest, Charges: 34472.841
Smoker: yes, Sex : female, Age: 22, Region: southeast, Charges: 35595.5898
Smoker: yes, Sex : male, Age: 19, Region: northwest, Charges: 16450.8947
Smoker: yes, Sex : male, Age: 18, Region: northeast, Charges: 13747.87235
Smoker: yes, Sex : male, Age: 22, Region: southeast, Charges: 37484.4493
Smoker: yes, Sex : male, Age: 20, Region: northeast, Charges: 33475.81715
Smoker: yes, Sex : male, Age: 22, Region: southeast, Charges: 44501.3982
Smoker: yes, Sex : male, Age: 28, Region: southeast, Charges: 34672.1472
Smoker: yes, Sex : female, Age: 22, Region: northwest, Charges: 33907.548
Smoker: yes, Sex : male, Age: 25, Region: southeast, Charges: 36124.5737
Smoker: yes, Sex : female, Age: 23, Region: southwest, Charges: 34166.273
Smoker: yes, Sex : female, Age: 23, Region: northeast, Charges: 40904.1995
Smoker: yes, Sex : female, Age: 19, Region: northwest, Charges: 36898.73308
Smoker: yes, Sex : male, Age: 19, Region: southeast, Charges: 39722.7462
Smoker: yes, Sex : male, Age: 18, Region: northeast, Charges: 17178.6824
Smoker: yes, Sex : female, Age: 23, Region: southeast, Charges: 18328.2381
Smoker: yes, Sex : male, Age: 20, Region: northwest, Charges: 37465.34375
Smoker: yes, Sex : female, Age: 19, Region: northwest, Charges: 33307.5508
Smoker: yes, Sex : female, Age: 18, Region: southeast, Charges: 18223.4512
Smoker: yes, Sex : female, Age: 20, Region: southeast, Charges: 26125.67477
Smoker: yes, Sex : female, Age: 20, Region: southwest, Charges: 20167.33603
Smoker: yes, Sex : male, Age: 24, Region: northeast, Charges: 18648.4217
Smoker: yes, Sex : male, Age: 20, Region: southwest, Charges: 16232.847
Smoker: yes, Sex : male, Age: 24, Region: northeast, Charges: 34254.05335
Smoker: yes, Sex : male, Age: 26, Region: southeast, Charges: 17043.3414
Smoker: yes, Sex : female, Age: 18, Region: northeast, Charges: 14283.4594
Smoker: yes, Sex : male, Age: 20, Region: southwest, Charges: 38344.566
Smoker: yes, Sex : male, Age: 19, Region: southwest, Charges: 34828.654
Smoker: yes, Sex : female, Age: 29, Region: northeast, Charges: 16115.3045
Smoker: yes, Sex : female, Age: 25, Region: southwest, Charges: 33900.653
Smoker: yes, Sex : female, Age: 19, Region: southwest, Charges: 36397.576